name: "Get Gradle Version"
description: "Extract version from Gradle and export it"
author: 'Marcos Martin <mmartin@paradigmadigital.com>'

outputs:
  VERSION:
    description: "Gradle version string"
    value: ${{ steps.get_version.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: get_version
      run: |
        VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT